### PR TITLE
ci: add GitHub Actions test workflow

### PR DESCRIPTION
**Pull request by owenvoke**
Things to think about:

- Add publishing to npm / GPR on Git tag
- Add Dependabot? 🤔

---

For the npm publishing, I guess we'd only want to do it on tag using something like:

```yml
# Publish to npm
- run: npm publish
  env:
    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

# Publish to GPR
- run: npm publish --registry https://npm.pkg.github.com
  env:
    NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

### CODE REVIEW

**Comment by owenvoke** [comment]
Thinking about it, the publishing should be added in another PR as it's a different action. 👍🏻

**Comment by owenvoke** [comment]
@sbrl, do you think this is ok to merge? 🤔

**Review by sbrl — APPROVED** [review]
Looks great - thanks, @owenvoke!

**Comment by owenvoke** [comment]
Well, that all passed! Great. 😀 https://github.com/tldr-pages/tldr-lint/actions

**Pull request merged**
