### PR TITLE
chore: move passing tests to 'passing' directory

### PR DESCRIPTION
**Pull request by owenvoke**
As mentioned in https://github.com/tldr-pages/tldr-lint/pull/30#issuecomment-755964914 👍🏻

I'm happy to add a "failing" directory as well, and move the other test pages if people would want that?

### CODE REVIEW

**Comment by waldyrious** [comment]
> I'm happy to add a "failing" directory as well, and move the other test pages if people would want that?

I'd like that! But even just this change is already an improvement. Thanks! 👍

**Comment by owenvoke** [comment]
Pushed 5a47f1e, which moves them to a failing directory. 👍🏻

**Comment by owenvoke** [comment]
@waldyrious, ok I've added a `.gitattributes` file, however it still won't register the line ending change. 🤔 Really confused...

**Comment by waldyrious** [comment]
Sorry, don't know enough about the nuances of configuring line endings in git to be of definitive help here. Could it be that the file has already been converted in your previous commit? Does this still happen if you try with a fresh clone of the project, and add the `.gitattributes` file before performing the file moving?

**Comment by owenvoke** [comment]
Well, now the line endings appear to change in 62ede3ca43091d0231d5b461ad8083630fe674ab (after force-pushing). However, the tests are now passing so I assume the line endings are CRLF?

**Comment by waldyrious** [comment]
That weird 🤔 but if the tests pass, I suppose it does work? 🤷 Maybe it's an issue with GitHub's diff... can you share the steps you took for the latest update to the PR?

**Comment by owenvoke** [comment]
1. `git reset --hard dbdb4e854f1520409f68c7eac07bbf3a3740aa5d` (roll-back to the original commit)
2. Add `.gitattributes` (https://github.com/tldr-pages/tldr-lint/blob/62ede3ca43091d0231d5b461ad8083630fe674ab/.gitattributes)
3. `git add . && git commit -m "chore: add Git attributes file"`
4. `mkdir specs/pages/failing && git mv specs/pages/*.md specs/pages/failing/` (and update Gitattributes and tests)
5. `git commit -m "chore: move failing tests to 'failing' directory`

**Comment by MasterOdin** [comment]
> That weird 🤔 but if the tests pass, I suppose it does work? 🤷 Maybe it's an issue with GitHub's diff... can you share the steps you took for the latest update to the PR?

The test will pass as the `.gitattributes` file will take effect on checkouts of the repo, so while the file is stored with `\n` here, on checkout it'll get `\r\n`.

From the current git commit, you can (I think do the following sequence to fix it):

```
git mv .gitattributes .gitattributes.bak && git commit -m "remove .gitattributes"
git config core.autocrlf false
wget https://raw.githubusercontent.com/tldr-pages/tldr-lint/master/specs/pages/010.md -O specs/pages/failing/010.md
git add . && git commit -m "set line endings to crlf"
git mv .gitattributes.bak .gitattributes && git commit -m "re-add .gitattributes
```

For the wget line, when I got it down, it showed a change, but when I did `git add .`, the change disappeared, and so I then had to convert it to `\n` (unix2dos), commit that, and then do the inverse (dos2unix), and then commit that, and I got the right file line ending. See https://github.com/MasterOdin/tldr-lint/tree/feature/examples-cleanup for an example of this sequence.

You'll then want to remove the `autoclrf` line from `.git/config` so that it uses the system setting again.

**Comment by owenvoke** [comment]
Sorry, I've been kind of busy recently. I can't seem to get this to commit correctly on my Mac. It just always shows that there's a change, even when there isn't. 😕

**Comment by MasterOdin** [comment]
@owenvoke I created #43 which fixes the file, while keeping the rest of the PR as-is.

**Comment by owenvoke** [comment]
Closed in favour of #43 👍🏻

**Pull request closed without merging**
