### PR TITLE
TravisCI integration

### PR DESCRIPTION
**Pull request by igorshubovych**
Integration with Travis CI.

This is what I see in my fork: http://take.ms/4I4SS

After merging you'll have to go to Travis and enable it.

### CODE REVIEW

**Comment by igorshubovych** [comment]
@rubenvereecken 
Don't be afraid by failures on screenshot. After you've merged #2, all should be green.

**Comment by rubenvereecken** [comment]
Oh so this would try a range of Node.js versions. Yeah that's pretty cool. Thanks! I've never written a Travis integration file from scratch, apparently it doesn't take too much.

I'll happily merge!

**Comment by igorshubovych** [comment]
@rubenvereecken 

Now you have to enable Travis.
This is how to do it: http://take.ms/nV9MR

**Comment by rubenvereecken** [comment]
I sent you a message on Gitter to discuss this.

**Pull request merged**
