### PR TITLE
incorporate eslint to project

### PR DESCRIPTION
**Pull request by MasterOdin**
This adds linting to the project, as there was a handful of style errors I would see when editing the files. This incorporates the same ruleset as tldr-pages/tldr-node-client and same pre-commit hook of running `npm run lint`.

### CODE REVIEW

**Review by bl-ue — CHANGES_REQUESTED** [review]
Can we use the string versions of the error levels instead of the numeric ones in `.eslintrc.json`? [docs](https://eslint.org/docs/user-guide/getting-started#configuration)

>"off" or 0 - turn the rule off
>"warn" or 1 - turn the rule on as a warning (doesn't affect exit code)
>"error" or 2 - turn the rule on as an error (exit code will be 1)

I like them because they're more readable.

**Comment by MasterOdin** [comment]
I would want buy in from @agnivade on that and then change the .eslintrc.json in the node client with the change as well to keep them in sync.

**Comment by agnivade** [comment]
I like it. Feel free to send a PR for the node client. :+1:

**Review by owenvoke — APPROVED** [review]

**Comment by MasterOdin** [comment]
@bl-ue done. I've also added a lint step to the GitHub workflow.

**Review by bl-ue — APPROVED** [review]

**Pull request merged**
