### PR TITLE
Add tldr-pages as copyright holder in License

### PR DESCRIPTION
**Pull request by MasterOdin**
This adds a new line to the license.md that recognizes that the tldr-pages organization are the current copyright holders.

I left @rubenvereecken's copyright line as the repo was originally under his account before it was transferred into the org, and it entered under the tldr-pages team's copyright.

### CODE REVIEW

**Comment by waldyrious** [comment]
> but not sure if there's a good email address to put for the tldr org, and just leave that blank.

Just dropping by to note that there's a mailing list, [tldr-pages@googlegroups.com](https://groups.google.com/g/tldr-pages/about), that could be used for this purpose. It never got much (well, any) traction, and the list of enrolled people hasn't been kept up to date with tldr-pages org members, but we could certainly sync them and use it for this purpose.

**Comment by rubenvereecken** [comment]
Appreciate the mention, I'm happy to be taken out completely. This project has long outlived my close involvement and happy to see it.

**Comment by sbrl** [comment]
Hmmm, seems like we can't merge this due to conflicts.

**Comment by owenvoke** [comment]
@sbrl, I don't see any conflicts when going to merge. 🤔

**Pull request merged**
