### PR TITLE
Add package-lock.json

### LINKED ISSUE #40: Why don't we commit package-lock.json?
Why don't we commit `package-log.json` as almost all Node.js/npm projects universally do?

```console
    $ npm install
    npm WARN deprecated nomnom@1.5.2: Package no longer supported. Contact support@npmjs.com for more info.
    npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
--> npm notice created a lockfile as package-lock.json. You should commit this file.
    npm WARN notsup Unsupported engine for jasmine@3.6.3: wanted: {"node":"^10 || ^12 || ^14"} (current: {"node":"15.4.0","npm":"6.14.8"})
    npm WARN notsup Not compatible with your version of node/npm: jasmine@3.6.3

    added 130 packages from 142 contributors and audited 130 packages in 3.359s

    7 packages are looking for funding
      run `npm fund` for details

    found 0 vulnerabilities
```

Quoting from https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json:
>This file is intended to be committed into source repositories, and serves various purposes:
>
>- Describe a single representation of a dependency tree such that teammates, deployments, and continuous integration are guaranteed to install exactly the same dependencies.
>
>- Provide a facility for users to "time-travel" to previous states of node_modules without having to commit the directory itself.
>
>- To facilitate greater visibility of tree changes through readable source control diffs.
>
>- And optimize the installation process by allowing npm to skip repeated metadata resolutions for previously-installed packages.

### PR DESCRIPTION
**Pull request by bl-ue**
Closes #40

cc @owenvoke

### CODE REVIEW

**Review by owenvoke — APPROVED** [review]
LGTM! Do you know anything about the differences of lockfile v1 and v2, and whether we should be using v2?

**Comment by owenvoke** [comment]
I'll update the CI when merged.

**Comment by bl-ue** [comment]
Oh oops! Sorry @owenvoke I forgot about this!

> Do you know anything about the differences of lockfile v1 and v2, and whether we should be using v2?

No, I'm sorry, I do not. 🤷🏻 

> Also do you mind updating this from npm i to npm ci?

Certainly! However it appears that you have already done it :D

**Comment by owenvoke** [comment]
No problem! I did some research, and it looks like `v2` is for npm v7 (unreleased). I'm hoping that Dependabot carries on using v1, until v2 is stable.

**Pull request merged**
